version: '3.9'

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env

  backend:
    build:
      context: ./services/backend
    restart: always
    env_file:
      - .env

## Only enable this if you want to use a local mongodb instance
#  db:  # This service name will be also used as hostname for MONGODB_URI
#    image: mongo:7.0.2
#    env_file:
#      - .env
#    volumes:
#      - mongodb-data:/data/db
#    restart: always

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env

## Only enable this if you want to use a local mongodb instance
# volumes:
#   mongodb-data:
