version: "3.9"
services:
    db:  # This service name will be also used as hostname for MONGODB_URI
      image: mongo:7.0.2
      env_file:
        - .env
      ports:
        - "27017:27017"
      volumes:
        - mongodb-data:/data/db
      restart: always

    burningbackend:
        build:
            context: ./
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - ${UVICORN_PORT}:${UVICORN_PORT}
        restart: always

volumes:
  mongodb-data: